/*
 * stm32c031xx_i2c_driver.c
 *
 *  Created on: 21-Jun-2026
 *      Author: prateek
 */


#include "stm32c031xx_i2c_driver.h"


static uint32_t RCC_GetPCLKValue(void);

uint16_t AHB_PreScaler[8] = {2, 4, 8, 16, 64, 128, 256, 512};
uint16_t APB1_PreScaler[4] = {2, 4, 8, 16};


uint32_t I2C_GetFlagStatus(I2C_RegDef_t *pI2Cx, uint32_t FlagName)
{
	if (pI2Cx->ISR & FlagName)
	{
		return I2C_FLAG_SET;
	}

    return I2C_FLAG_RESET;
}

PeriphStatus_t I2C_PClkCtrl(I2C_RegDef_t *pI2Cx, PeriphState_t pState)
{
    if (pI2Cx == NULL) return PERIPH_ERROR;

    if (pState == PERIPH_ENABLE) {
        if      (pI2Cx == I2C1) I2C1_PCLK_EN();
        else if (pI2Cx == I2C2) I2C2_PCLK_EN();
        else return PERIPH_ERROR;
    } else {
        if      (pI2Cx == I2C1) I2C1_PCLK_CLR();
        else if (pI2Cx == I2C2) I2C2_PCLK_CLR();
        else return PERIPH_ERROR;
    }
    return PERIPH_OK;
}


PeriphStatus_t I2C_Init(I2C_Handle_t *pI2CHandle)
{
    uint32_t tempreg = 0;

    /* Disable peripheral */
//    pI2CHandle->pI2Cx->CR1 &= ~(1 << I2C_CR1_PE);

    /* Configure own address */
    tempreg = (1 << 15);      // OA1EN

    if(pI2CHandle->I2C_Config.I2C_DeviceAddress <= 0x7F)
    {
        tempreg |= (pI2CHandle->I2C_Config.I2C_DeviceAddress << 1);
    }
    else
    {
        tempreg |= (1 << 10);      // OA1MODE
        tempreg |= (pI2CHandle->I2C_Config.I2C_DeviceAddress & 0x3FF);
    }

    pI2CHandle->pI2Cx->OAR1 = tempreg;

    /* Configure timing */
    tempreg = 0;

    tempreg |= ((pI2CHandle->I2C_Config.I2C_SCL.PRESC_VALUE & 0xF) << 28);
    tempreg |= ((pI2CHandle->I2C_Config.I2C_SCL.SCLDEL_VALUE & 0xF) << 20);
    tempreg |= ((pI2CHandle->I2C_Config.I2C_SCL.SDADEL_VALUE & 0xF) << 16);
    tempreg |= ((pI2CHandle->I2C_Config.I2C_SCL.SCLH_VALUE & 0xFF) << 8);
    tempreg |= ((pI2CHandle->I2C_Config.I2C_SCL.SCLL_VALUE & 0xFF));

    pI2CHandle->pI2Cx->TIMINGR = tempreg;

    /* Enable peripheral */
//    pI2CHandle->pI2Cx->CR1 |= (1 << I2C_CR1_PE);

    return PERIPH_OK;
}

PeriphStatus_t I2C_DeInit(I2C_RegDef_t *pI2Cx)
{
    if      (pI2Cx == I2C1) I2C1_REG_RESET();
    else if (pI2Cx == I2C2) I2C2_REG_RESET();
    else return PERIPH_ERROR;
    return PERIPH_OK;
}


void I2C_PCtrl(I2C_RegDef_t *pI2Cx, PeriphState_t pState)
{
	if (pState == PERIPH_ENABLE)
	{
		pI2Cx->CR1 |= (1 << I2C_CR1_PE);
	}
	else
	{
		pI2Cx->CR1 &= ~(1 << I2C_CR1_PE);
	}
}



PeriphStatus_t I2C_Master_SendData(I2C_Handle_t *pI2CHandle, uint8_t *pTxBuffer, uint32_t len, uint16_t SlaveAddr)
{
    uint32_t tmpreg = 0;

    /* NULL pointer */
    if (pTxBuffer == NULL)
        return PERIPH_ERROR;

    /* Wait until bus becomes free */
    while (I2C_GetFlagStatus(pI2CHandle->pI2Cx, I2C_FLAG_BUSY));

    /* Clear CR2 before programming new transfer */
    pI2CHandle->pI2Cx->CR2 = 0;

    /* Configure slave address */
    if (SlaveAddr <= 0x7F)
    {
        /* 7-bit address */
        tmpreg |= ((uint32_t)SlaveAddr << I2C_CR2_SADD);
    }
    else
    {
        /* 10-bit address */
        tmpreg |= (1U << I2C_CR2_ADD10);
        tmpreg |= (SlaveAddr & 0x3FF);
    }

    /* Number of bytes */
    tmpreg |= ((len & 0xFFU) << I2C_CR2_NBYTES);

    /* Generate STOP automatically after NBYTES transferred */
    tmpreg |= (1U << I2C_CR2_AUTOEND);

    /* Need to set the direction */
//    tempreg |= (0 << I2C_CR2_RD_WRN);

    /* Generate START */
    tmpreg |= (1U << I2C_CR2_START);

    /* Start transfer */
    pI2CHandle->pI2Cx->CR2 = tmpreg;

    /* Send data */
    while (len > 0)
    {
        /* Wait until TXDR is ready or error occurs */
        while (!I2C_GetFlagStatus(pI2CHandle->pI2Cx, I2C_FLAG_TXIS))
        {
            /* Address or data NACKed */
            if (I2C_GetFlagStatus(pI2CHandle->pI2Cx, I2C_FLAG_NACKF))
            {
                pI2CHandle->pI2Cx->ICR |= (1 << I2C_ICR_NACKCF);
                return PERIPH_ERROR;
            }
        }

        /* Write one byte */
        pI2CHandle->pI2Cx->TXDR = *pTxBuffer;

        pTxBuffer++;
        len--;
    }

    /* Wait until STOP generated by AUTOEND */
    while (!I2C_GetFlagStatus(pI2CHandle->pI2Cx, I2C_FLAG_STOPF));

    /* Clear STOP flag */
    pI2CHandle->pI2Cx->ICR |= (1 << I2C_ICR_STOPCF);

    return PERIPH_OK;
}


static uint32_t RCC_GetPCLKValue(void)
{
	uint32_t pclk1; // Frequency value of clock
	uint32_t SystemClk;

	uint8_t clksrc; // HSI/HSE/PLL/etc.
	uint8_t temp;
	uint8_t ahbp /* AHB1 prescaler */, apb1p /* APB1 prescaler */;

	clksrc = (RCC->CFGR >> 3) & 0x7; // bit[0:1] : SWS bit

	switch(clksrc)
	{
		case 0: // HSISYS
		case 1: // HSE
			SystemClk = 48000000; // 8 MHz : STM32F407xx external oscillator
			break;

		case 2: // only for stm32c071xx
			break;

		case 3: // LSI
			SystemClk = 32000000; // 8 MHz : STM32F407xx external oscillator
			break;

		case 4: // LSE
			SystemClk = 32768000; // 8 MHz : STM32F407xx external oscillator
			break;
		default:
			SystemClk = 0;
			break;
	}

	/* Finding out AHB1 prescaler */
	temp = ((RCC->CFGR >> 8) & 0xF);

	if (temp < 8)
	{
		ahbp = 1;
	}
	else
	{
		// Refer to reference manual, page 169 : bit[7:4]
		ahbp = AHB_PreScaler[temp - 8];
	}

	/* Finding out APB1 prescaler */
	temp = ((RCC->CFGR >> 12) & 0x7);

	if (temp < 4)
	{
		apb1p = 1;
	}
	else
	{
		// Refer to reference manual, page 168 : bit[12:10]
		apb1p = APB1_PreScaler[temp - 4];
	}

	pclk1 = (SystemClk / ahbp) / apb1p;

	return pclk1;
}


void I2C_IRQPriorityConfig(uint8_t IRQNumber,uint32_t IRQPriority)
{

}


void I2C_IRQInterruptConfig(uint8_t IRQNumber, PeriphState_t EnorDi)
{

}


