/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <string.h>
#include "stm32c031xx.h"
#include "stm32c031xx_gpio_driver.h"
#include "stm32c031xx_systick_timer.h"
#include "stm32c031xx_spi_driver.h"

#define ACK  0xF5
#define NACK 0xFF

extern void initialise_monitor_handles(void);

void SPI_GPIOInits(void)
{
	GPIO_Handle_t SPIPins;

	SPIPins.pGPIOx = GPIOA;
	SPIPins.GPIO_PinConfig.GPIO_PinMode = GPIO_ALTFN;
	SPIPins.GPIO_PinConfig.GPIO_PinAltFunMode = 0; // AF0 for SPI1
	SPIPins.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	SPIPins.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	SPIPins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

	// SCLK
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_NO_5;
	GPIO_Init(&SPIPins);

	// MOSI
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_NO_7;
	GPIO_Init(&SPIPins);

	// MISO
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_NO_6;
	GPIO_Init(&SPIPins);

	// NSS (software)
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_NO_4;
	GPIO_Init(&SPIPins);
}


void SPI1_Inits(void)
{
    SPI_Handle_t SPI1handle;
    SPI1handle.pSPIx                       = SPI1;
    SPI1handle.SPIConfig.SPI_BusConfig     = SPI_BUS_CONFIG_FD;
    SPI1handle.SPIConfig.SPI_DeviceMode    = SPI_DEVICE_SLAVE_MODE;
    SPI1handle.SPIConfig.SPI_SclkSpeed     = SPI_SCLK_SPEED_DIV2;
    SPI1handle.SPIConfig.SPI_CPHA          = SPI_CPHA_LOW;
    SPI1handle.SPIConfig.SPI_CPOL          = SPI_CPOL_LOW;
    SPI1handle.SPIConfig.SPI_DS            = SPI_DS_8BITS;
    SPI1handle.SPIConfig.SPI_SSM           = SPI_SSM_DI;
    SPI1handle.SPIConfig.SPI_Endian		   = SPI_little_end;
    SPI1handle.SPIConfig.SPI_FRXTH		   = SPI_RXNE_8;

    SPI1handle.SPIConfig.SPI_CRCCalculation = SPI_CRC_EN;
    SPI1handle.SPIConfig.SPI_CRCPolynomial = 0x07;

	(void)SPI_Init(&SPI1handle);
}


int main(void)
{
    uint8_t cmd_rx, ack_tx, dummy_rx;
    uint8_t dummy_tx = NACK; // 0xFF
    uint8_t cmd[5] = {10, 20, 30, 40, 50};
    uint8_t idx = 0;

    initialise_monitor_handles();
    init_systick(1000, 0);
    SPI_GPIOInits();
    SPI1_Inits();
    SPI_SSOEConfig(SPI1, PERIPH_DISABLE);

    printf("Slave Ready\n");

    while (1)
    {
        // --- PHASE 1: Wait for and Receive Command ---
        SPI_PCtrl(SPI1, PERIPH_ENABLE);
        if(SPI_TransmitReceiveData(SPI1, &dummy_tx, &cmd_rx, 1) == PERIPH_ERROR) {
            printf("Slave CRC Error on Phase 1\n");
        }
        // Immediately reset CRC calculator when the CS boundary ends
        SPI_ClearCRC(SPI1);

        // Evaluate Command
        ack_tx = (cmd_rx == cmd[idx]) ? ACK : NACK;

        // --- PHASE 2: Transmit the prepared ACK ---
        SPI_PCtrl(SPI1, PERIPH_ENABLE);
        if(SPI_TransmitReceiveData(SPI1, &ack_tx, &dummy_rx, 1) == PERIPH_ERROR) {
            printf("Slave CRC Error on Phase 2\n");
        }
        SPI_ClearCRC(SPI1);

        printf("Data received: %d | Sent ACK: 0x%X\n", cmd_rx, ack_tx);
        idx = (idx + 1) % 5;
    }
}
