///**
// ******************************************************************************
// * @file           : main.c
// * @author         : Auto-generated by STM32CubeIDE
// * @brief          : Main program body
// ******************************************************************************
// * @attention
// *
// * Copyright (c) 2026 STMicroelectronics.
// * All rights reserved.
// *
// * This software is licensed under terms that can be found in the LICENSE file
// * in the root directory of this software component.
// * If no LICENSE file comes with this software, it is provided AS-IS.
// *
// ******************************************************************************
// */
//
#include <stdio.h>
#include <string.h>
#include "stm32c031xx.h"
#include "stm32c031xx_gpio_driver.h"
#include "stm32c031xx_systick_timer.h"
#include "stm32c031xx_spi_driver.h"
//
extern void initialise_monitor_handles(void);
//
void SPI_GPIOInits(void)
{
	GPIO_Handle_t SPIPins;

	SPIPins.pGPIOx = GPIOA;
	SPIPins.GPIO_PinConfig.GPIO_PinMode = GPIO_ALTFN;
	SPIPins.GPIO_PinConfig.GPIO_PinAltFunMode = 0; // AF0 for SPI1
	SPIPins.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	SPIPins.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	SPIPins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;

	// SCLK
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_NO_5;
	GPIO_Init(&SPIPins);

	// MOSI
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_NO_7;
	GPIO_Init(&SPIPins);

	// MISO
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_NO_6;
	GPIO_Init(&SPIPins);

	// NSS (software)
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_NO_4;
	GPIO_Init(&SPIPins);
}


void SPI1_Inits(void)
{
	SPI_Handle_t SPI1handle;
	SPI1handle.pSPIx = SPI1;
	SPI1handle.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;
	SPI1handle.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MASTER_MODE;
	SPI1handle.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV8; // 8 MHz
	SPI1handle.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
	SPI1handle.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
	SPI1handle.SPIConfig.SPI_DS = SPI_DS_8BITS;
	SPI1handle.SPIConfig.SPI_SSM = SPI_SSM_EN; // software slave management for NSS pin

	(void)SPI_Init(&SPI1handle);
}


void Button_Init(void)
{
	GPIO_Handle_t GpioBtn;
	memset(&GpioBtn, 0, sizeof(GpioBtn));
	//	(void)GPIO_PClkCtrl(GPIOA, PERIPH_ENABLE);

	GpioBtn.pGPIOx = GPIOC;
	GpioBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_NO_13;
	GpioBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_IT_FT;
	GpioBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	(void)GPIO_Init(&GpioBtn);

	//	(void)GPIO_PClkCtrl(GPIOC, PERIPH_ENABLE);

	GPIO_EXTIConfig(GPIOC, GPIO_NO_13, GPIO_IT_FT);

	// IRQ Configurations
	GPIO_IRQPriorityConfig(IRQ_NO_EXTI4_15, NVIC_IRQ_PRI3);
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI4_15, PERIPH_ENABLE);

	//	GPIO_IRQPriorityConfig(IRQ_NO_EXTI0_1, NVIC_IRQ_PRI3);
	//	GPIO_IRQInterruptConfig(IRQ_NO_EXTI0_1, PERIPH_ENABLE);
}

int main(void) {

	char user_data[] = "Hello world";

//	initialise_monitor_handles();

//	init_systick(1000, 0);

	SPI_GPIOInits();

//	Button_Init();

	SPI1_Inits();

	SPI_SSIConfig(SPI1, PERIPH_ENABLE);

	SPI_PCtrl(SPI1, PERIPH_ENABLE);

	SPI_SendData(SPI1, (uint8_t*)user_data, strlen(user_data));

	SPI_PCtrl(SPI1, PERIPH_DISABLE);

	for(;;);

	return 0;
}

void EXTI4_15_IRQHandler(void)
//void EXTI0_1_IRQHandler(void)
{
	GPIO_IRQHandling(GPIO_NO_13);

	delay_ms(1000);

	SPI_PCtrl(SPI1, PERIPH_ENABLE);

	char user_data[] = "Hello world";

	SPI_SendData(SPI1, (uint8_t*)user_data, strlen(user_data));

	SPI_PCtrl(SPI1, PERIPH_DISABLE);
}

