/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <string.h>
#include "stm32c031xx.h"
#include "stm32c031xx_gpio_driver.h"
#include "stm32c031xx_systick_timer.h"
#include "stm32c031xx_spi_driver.h"

extern void initialise_monitor_handles(void);

void SPI_GPIOInits(void)
{
	GPIO_Handle_t SPIPins;

	SPIPins.pGPIOx = GPIOA;
	SPIPins.GPIO_PinConfig.GPIO_PinMode = GPIO_ALTFN;
	SPIPins.GPIO_PinConfig.GPIO_PinAltFunMode = 0; // AF0 for SPI1
	SPIPins.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	SPIPins.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	SPIPins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

	// SCLK
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_NO_5;
	GPIO_Init(&SPIPins);

	// MOSI
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_NO_7;
	GPIO_Init(&SPIPins);

	// MISO
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_NO_6;
	GPIO_Init(&SPIPins);

	// NSS (software)
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_NO_4;
	GPIO_Init(&SPIPins);
}


void SPI1_Inits(void)
{
	SPI_Handle_t SPI1handle;
	SPI1handle.pSPIx = SPI1;
	SPI1handle.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;
	SPI1handle.SPIConfig.SPI_DeviceMode = SPI_DEVICE_SLAVE_MODE;
	SPI1handle.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV2; // 8 MHz
	SPI1handle.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
	SPI1handle.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
	SPI1handle.SPIConfig.SPI_DS = SPI_DS_8BITS;
	SPI1handle.SPIConfig.SPI_SSM = SPI_SSM_EN; // software slave management for NSS pin

	(void)SPI_Init(&SPI1handle);
}


int main(void)
{
//	char user_data[] = "..... .....";
	uint8_t byte;

	initialise_monitor_handles();

	printf("Hello world\n");

	init_systick(1000, 0);

	SPI_GPIOInits();

	SPI1_Inits();

	SPI_SSIConfig(SPI1, PERIPH_DISABLE);

	SPI_PCtrl(SPI1, PERIPH_ENABLE);

	while (1)
	{
		SPI_ReceiveData(SPI1, &byte, 1);

		delay_ms(1000);

		while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));

		printf("data received : %d\n", byte);
	}

	SPI_PCtrl(SPI1, PERIPH_DISABLE);

	for(;;);
}

